services:
  postgres:
    image: postgres:16
    container_name: postgres-canchat-change-role
    restart: unless-stopped
    environment:
      POSTGRES_USER: canchat
      POSTGRES_PASSWORD: canchatpass
      POSTGRES_DB: canchatdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}