nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ghcr.io/ssc-dsai/canchat-role-change-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

prefix:
  app: "/test-role-change"
  api: "/api/v1"

appEnv: "prod" # e.g. dev, uat, prod

allowedOrigins: []
  # e.g. 
  # - "*"
  # - "https://mydomain.com"
  # - "https://myotherdomain.com"
  
allowedRoles: 
  - "user"
  - "pending"
  - "analyst"
  - "global_analyst"


database:
  url: ""
  caCrt: ""
    # -----BEGIN CERTIFICATE-----
    # ...
    # -----END CERTIFICATE-----

extraEnvVars: []
#  - name: CUSTOM_ENV_VAR
#    value: "custom_value"
  # - name: CUSTOM_ENV_VAR_FROM_SECRET
  #   valueFrom:
  #     secretKeyRef:
  #       key: CUSTOM_ENV_VAR_FROM_SECRET
  #       name: CUSTOM_SECRET_NAME

externalVolumes: []
  # - name: my-external-volume
  #   secret:
  #      secretName: my-cert-secret
  # - name: another-volume
  #   configMap:
  #      configMapName: some-config

externalVolumesMounts: []
  # - name: my-external-volume
  #   mountPath: /path/in/container
  #   readOnly: true

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}